FROM microcloud/centos-consul
MAINTAINER omeid@microcloud.io

RUN yum -y install  http://yum.postgresql.org/9.3/redhat/rhel-6-x86_64/pgdg-centos93-9.3-1.noarch.rpm 
RUN yum -y upgrade
RUN yum -y install postgresql93-server
